//Javascript
$('#Sunday').click(function(){
    $('body').css('background-color','')
    $('.accordion-body').css('background-color','#006BEE')
    $('h3').css('color','white')
    $('p').css('color','white')
})
$('#Monday').click(function(){
    $('body').css('background-color','')
    $('.accordion-body').css('background-color','#006BEE')
    $('h3').css('color','white')
    $('p').css('color','white')
})
$('#tuesday').click(function(){
    $('body').css('background-color','')
    $('.accordion-body').css('background-color','#006BEE')
    $('h3').css('color','white')
    $('p').css('color','white')
})
$('#wensday').click(function(){
    $('body').css('background-color','')
    $('.accordion-body').css('background-color','#006BEE')
    $('h3').css('color','white')
    $('p').css('color','white')
})
$('#thursday').click(function(){
    $('body').css('background-image','')
    $('.accordion-body').css('background-color','#006BEE')
    $('h3').css('color','white')
    $('p').css('color','white')
})
$('#friday').click(function(){
    $('body').css('background-color','')
    $('.accordion-body').css('background-color','#006BEE')
    $('h3').css('color','white')
    $('p').css('color','white')
})
$('#Saturday').click(function(){
    $('body').css('background-image','')
    $('.accordion-body').css('background-color','#006BEE')
    $('h3').css('color','white')
    $('p').css('color','white')
})